# Splitting by multiple groups
# gdp_by_industry_oceania contains the GDP generated by the agriculture and tourism industries in both 1995 and 2010. Your goal is to create a wide format data.table containing columns of GDP for each year and industry.
# 
# Instructions
# 100 XP
# Print gdp_by_industry_oceania.
# Convert gdp_by_industry_oceania to a wide format with each country as a row, splitting the "gdp" column so that the result has columns containing the gdp for each industry and each year.

# Split gdp by industry and year
dcast(gdp_by_industry_oceania, country ~ industry + year, value.var = "gdp")